### ISSUE TITLE
Upgrade to WildFly 9

### ISSUE THREAD

**Issue by Sanne** [fharms/java-examples#3]
Hello, may I suggest to upgrade to WildFly 9. I know it's not released yet, let's do it as soon as it is as it's going to be released very soon.

The reason is it already includes:
- Infinispan 7.1.1.Final
- Hibernate Search 5.1.2.Final

So while you'd still need to download Hibernate OGM, the overall setup experience for someone to follow the guide should be much improved.

**Comment by Sanne** [comment]
BTW I'll document the details in the Hibernate OGM project as soon as it's out so it should be a simple step ;-)

**Comment by fharms** [comment]
Thanks for the feedback Sanne

I think I will create a profile for both Wildfly 8 and Wildfly 9 and update the README.md how to install for Wildfly 9. We will stick with Wildfly 8 for a while, at least to 9.1 is released, and there properly others who could benefit for the Wildfly 8 guide

**Comment by fharms** [comment]
Better late then never. I have upgraded to Wildfly 10 and Hibernate OGM 5 :-)
